import { Header } from '@/components/Header'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={`bg-base-gray-600 text-base-gray-100 ${inter.className}`}
      >
        <Header />
        <div className="mx-auto -mt-[102px] max-w-3xl px-6">{children}</div>
      </body>
    </html>
  )
}
